name: Workflow template for Core Linting CI jobs
on:
  workflow_call:

jobs:
  code_lint:
    runs-on: [matterlabs-ci-runner]

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          submodules: "recursive"

      - name: Setup environment
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env

      - name: Start services
        run: |
          mkdir -p ./volumes/postgres
          run_retried docker compose pull zk postgres
          docker compose up -d zk postgres
          ci_run sccache --start-server

      - name: Build
        run: |
          ci_run bash -c "cd zk_toolbox && cargo build --release"
          cp ./zk_toolbox/target/release/zk_supervisor ./bin
          cp ./zk_toolbox/target/release/zk_inception ./bin
          ci_run bash -c "yarn install"
          ci_run bash -c "git config --global --add safe.directory /usr/src/zksync"

      - name: Setup db
        run: |
          ci_run zk_inception ecosystem init --dev
          ci_run zk_supervisor database prepare

      - name: Lints
        run: |
          ci_run zk_supervisor fmt --check
          ci_run zk_supervisor lint -e md --check
          ci_run zk_supervisor lint -e sol --check
          ci_run zk_supervisor lint -e js --check
          ci_run zk_supervisor lint -e ts --check
          ci_run zk_supervisor lint -e rs --check
          ci_run zk_supervisor database check-sqlx-data
