name: Workflow template for Core Linting CI jobs
on:
  workflow_call:

jobs:
  code_lint:
    runs-on: [matterlabs-ci-runner]

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          submodules: "recursive"
          fetch-depth: 0

      - name: Download zk_toolbox binaries
        uses: actions/download-artifact@v4
        with:
          name: zk_toolbox
          path: .

      - name: Extract zk_toolbox binaries
        run: |
          tar -xvf zk_toolbox.tar -C ./bin

      - name: Setup environment
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env

      - name: Lints
        run: |
          ci_run zks fmt --check
          ci_run zks lint -e md --check
          ci_run zks lint -e sol --check
          ci_run zks lint -e js --check
          ci_run zks lint -e ts --check
          ci_run zks lint -e rs --check
