name: Workflow template for Core Linting CI jobs
on:
  workflow_call:

jobs:
  code_lint:
    runs-on: [matterlabs-ci-runner]
    needs: [build]

    steps:
      - name: Setup environment
        run: |
          echo ZKSYNC_HOME=$(pwd) >> $GITHUB_ENV
          echo $(pwd)/bin >> $GITHUB_PATH
          echo IN_DOCKER=1 >> .env

      - name: Start services
        run: |
          ci_localnet_up
          ci_run sccache --start-server

      - name: Lints
        run: |
          ci_run zks fmt --check
          ci_run zks lint -e md --check
          ci_run zks lint -e sol --check
          ci_run zks lint -e js --check
          ci_run zks lint -e ts --check
          ci_run zks lint -e rs --check
